name: AppShell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest
    container:
      image: node:22
      env:
        APP_ENV: development
        NODE_ENV: development
        DATABASE_URL: fake_database_url_for_ci

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
        name: Install dependencies

      - run: npm run prisma:generate
        name: Generate Prisma client

      - run: cd generated/prisma && ls && npm run test
        name: Run tests

      - run: npm run build
        name: Build project
